# Generated by Django 4.2 on 2023-05-03 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='SizeVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=20)),
                ('category', models.CharField(choices=[('M', 'Mobile'), ('L', 'Laptop'), ('TW', 'Top Wear'), ('BW', 'Bottom Wear'), ('S', 'Shoes'), ('W', 'Watch')], default=1, max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Subcategory',
        ),
        migrations.AddField(
            model_name='product',
            name='bottomwear_sizes',
            field=models.ManyToManyField(blank=True, related_name='bottomwear_sizes', to='app.sizevariant'),
        ),
        migrations.AddField(
            model_name='product',
            name='shoe_sizes',
            field=models.ManyToManyField(blank=True, related_name='shoe_sizes', to='app.sizevariant'),
        ),
        migrations.AddField(
            model_name='product',
            name='topwear_sizes',
            field=models.ManyToManyField(blank=True, related_name='topwear_sizes', to='app.sizevariant'),
        ),
    ]
